# **Lab 1: Preprocessing & Data Wrangling**

**Course**: **INS-605: Data Analysis** <br>
**Lecturer**: **Sothea HAS, PhD**

-----

**Objective:** In this lab, we will work with real-world product review data (`Amazon Product Reviews`) to practice key data wrangling techniques discussed in the lecture: inspecting raw data, handling missing values, converting data types, feature transformation, grouping/aggregation, combining datasets, and reshaping data.

> The notebook of the lab can be downloaded from [Lab1: Proprocessing & Data Wrangling](https://hassothea.github.io/AUPP_Data_Analysis_II/Labs/Lab1/01-data-wrangling.ipynb){target="_blank"}.

-----

- Student name: Laimeng EUNG
- ID: 2024440

> **Submission:** You must do the followings
> 
> - Name your file as: `Lab1_name.ipynb`
> - Submit this jupyter notebook file (`Lab1_name.ipynb`) to Canvas, NOT THE COLAB LINK!


-----

## **1. Importing and Inspecting the Data**

We will explore the **Amazon Product Reviews** dataset from Kaggle (`arhamrumi/amazon-product-reviews`). Let's download and load the dataset into pandas.

In [1]:
#| echo: ture
#| code-fold: true

# %pip install kagglehub

import kagglehub
import pandas as pd
import os

# Download latest version
path = kagglehub.dataset_download("arhamrumi/amazon-product-reviews")

# Load data (locate the CSV file in the downloaded path)
file_name = [f for f in os.listdir(path) if f.endswith('.csv')][0]
data = pd.read_csv(f"{path}/{file_name}")
data.head()

c:\Users\eungl\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.4.0) or chardet (7.4.3)/charset_normalizer (3.4.1) doesn't match a supported version!
  warnings.warn(

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

-------

### **1.1. Overview of the data**

Before cleaning, inspect the structure of the dataset and answer the following:

**A.** Check the dimension of the dataset (`shape`). How many rows and columns are there?

**B.** What are the data types of each column (`dtypes`)? Identify columns whose data types do not match their intended semantic meaning.

**C.** Check for missing values (`isna().sum()`). Which columns contain `NaN` values, and how many are missing in each column?

**D.** Are there any duplicated rows in this dataset? Calculate the total number of duplicates using `.duplicated().sum()`.

**E.** Check the number of unique values in each column (`nunique()`). 

- **E.1.** Compare the number of unique `UserId`s to unique `ProfileName`s. Why do you think we observed such numbers?
- **E.2.** Do missing names in `ProfileName` potentially share a `UserId` with non-missing rows? This will guide our imputation strategy.
  
**F.** Check if missing `ProfileName`s are related to missing `Summary`s.

In [2]:
# Let's find out!
# A.
data.shape

(568454, 10)

In [3]:
# B. Type
data.dtypes

Id                         int64
ProductId                 object
UserId                    object
ProfileName               object
HelpfulnessNumerator       int64
HelpfulnessDenominator     int64
Score                      int64
Time                       int64
Summary                   object
Text                      object
dtype: object

`Time` has the wrong data type. It should be `date` instead of `int64`

In [4]:
# Missing values
data.isna().sum()

Id                         0
ProductId                  0
UserId                     0
ProfileName               26
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

`ProfileName` and `Summary` has 26 and 27 missing values, respectively.

In [5]:
# D. Check for duplicated values
data.duplicated().sum()

np.int64(0)

There are 0 duplicate row.

**E.** Check the number of unique values in each column (`nunique()`). 

- **E.1.** Compare the number of unique `UserId`s to unique `ProfileName`s. Why do you think we observed such numbers?
- **E.2.** Do missing names in `ProfileName` potentially share a `UserId` with non-missing rows? This will guide our imputation strategy.
  
**F.** Check if missing `ProfileName`s are related to missing `Summary`s.

In [6]:
# E. Check for unique values in each column
data.nunique()

Id                        568454
ProductId                  74258
UserId                    256059
ProfileName               218415
HelpfulnessNumerator         231
HelpfulnessDenominator       234
Score                          5
Time                        3168
Summary                   295742
Text                      393579
dtype: int64

In [7]:
# E.1: compare the unique UserID to ProfileName
# Check for UserId with missing profile name
missing_names = data[['UserId', 'ProfileName']].query("ProfileName.isna()")
missing_names

                UserId ProfileName
10616   A1LSYR30XW7CFT         NaN
25509   A36BVYD0NT7Z0F         NaN
38874   A36BVYD0NT7Z0F         NaN
47923   A2DEHJJIEAPPBF         NaN
49800   A2LYFY32LXQDON         NaN
67077   A2P0P67Y55SNOX         NaN
106550  A1P500QXEG3IUZ         NaN
121819  A34F9B57SYQ5XR         NaN
125452  A34F9B57SYQ5XR         NaN
137613   AGT3BYX5P9SLH         NaN
163191   AGT3BYX5P9SLH         NaN
172462   AC9U70TRGPDGJ         NaN
211846  A2DEHJJIEAPPBF         NaN
268648  A2DEHJJIEAPPBF         NaN
297275  A29D7XVSBCLFLD         NaN
306751   AGT3BYX5P9SLH         NaN
331647  A1PZJLGDQSLZWE         NaN
358674  A2DEHJJIEAPPBF         NaN
431598  A36BVYD0NT7Z0F         NaN
440825   AC0E8TXIYABB5         NaN
461668  A34F9B57SYQ5XR         NaN
490412   AGT3BYX5P9SLH         NaN
491728  A29D7XVSBCLFLD         NaN
515436  A2H7605OSHVIQ5         NaN
517676  A1VIUQE908L3M3         NaN
560446   AGT3BYX5P9SLH         NaN

In [8]:
missing_names.shape

(26, 2)

In [9]:
# missing_names.query('ProfileName.isna()')
# Dropping NAN of either UserId or ProfileName
# .first() flatten each UserId group into a single ProfileName string so Pandas can format the result into a key-value dictionary.
name_map = data[['UserId', 'ProfileName']].dropna().groupby('UserId').first().to_dict()
name_map['ProfileName']

{'#oc-R103C0QSV1DF5E': 'C',
 '#oc-R109MU5OBBZ59U': 'AayGee',
 '#oc-R10LFEMQEW6QGZ': 'Julie',
 '#oc-R10LT57ZGIB140': 'dipr',
 '#oc-R10UA029WVWIUI': 'Kim D',
 '#oc-R115TNMSPFT9I7': 'Breyton',
 '#oc-R119LM8D59ZW8Y': 'Lee Mellott "SEOmenu2go"',
 '#oc-R11D9D7SHXIJB9': 'Louis E. Emory "hoppy"',
 '#oc-R11D9LKDAN5NQJ': 'Melissa Korducavich',
 '#oc-R11DNU2NBKQ23Z': 'Kim Cieszykowski',
 '#oc-R11O5J5ZVQE25C': 'Penguin Chick',
 '#oc-R11PW3CFBB4BEP': 'Thomas "mrpalmer420"',
 '#oc-R11T1PHWNO7KEZ': 'David Zeitler',
 '#oc-R120LO6OLNDPCG': 'cjl',
 '#oc-R12KPBODL2B5ZD': 'Christopher P. Presta',
 '#oc-R12MGTQS5KZZRV': 'SKY2110 "SKY2110"',
 '#oc-R12N3533IO3B79': 'kat',
 '#oc-R13EBF129DBX88': 'mary',
 '#oc-R13NNUL4EKL4FL': 'N. Chernyavskaya',
 '#oc-R13X3YIJ6GLT0C': 'P. McCoy "Friend of Bill W. and Dr. Bob"',
 '#oc-R1493EDK6REQ02': 'Robud48',
 '#oc-R149FDXLRARCWJ': 'Alicia Johnson',
 '#oc-R14VLCY75KIBSB': 'steve "Steve"',
 '#oc-R14ZSRYW2YB41B': 'A. Crafton',
 '#oc-R14ZUK54VMOGJS': 'Dave',
 '#oc-R1522DF2LUL4G1': 'michaelp',
 '#oc-R152UR09M996EM': 'Ray',
 '#oc-R15343ZW0UTLMR': 'Lisa L. Nolen "SimplyLisaLisa"',
 '#oc-R155JB2SA58E17': 'Seanna',
 '#oc-R15LBVAVIE5O2X': 'Richard Jacobson',
 '#oc-R15OCG1KF51S4F': 'hrmajsty',
 '#oc-R162D7S0A880MV': 'Jish M.',
 '#oc-R163CP16SRRI50': 'Jennifer L. Vido',
 '#oc-R1669TSD0WO7EP': 'tabo',
 '#oc-R16HPROGAO1HS6': 'Jennifer',
 '#oc-R1730HL4795MHX': 'Julia K. Handzo',
 '#oc-R1791MZMDMM68R': 'D. Hines',
 '#oc-R17KN3F3UGQSU0': 'Janis Fine',
 '#oc-R18VQWFOMHGFVE': 'Deborah Tabor',
 '#oc-R18WCIOVC1O7U3': 'frabrooke',
 '#oc-R18WQYZLWDZTSW': 'J. Le "Callandor"',
 '#oc-R18XETRRZHQVPE': 'Robertm3210',
 '#oc-R192YGWMM86YIU': 'J. Fred Madden "JFRED"',
 '#oc-R19B7LHEK1ARMD': 'kelli n',
 '#oc-R19EJ3VEA88T6O': 'Delaney',
 '#oc-R19QDOY2PXS15': 'Andrew',
 '#oc-R19TGMUT9ZUY0G': 'R. Mendez',
 '#oc-R19W3DMF9X0I7C': 'bonnie',
 '#oc-R1A1AOCIP53NOM': 'REMO35 "REMO35"',
 '#oc-R1A8CVV3LZ4W8Q': 'Cherinleligh',
 '#oc-R1AQH0RQMTL1Y9': 'MarkL',
 '#oc-R1AYD24FXE1MV7': 'Historian66',
 '#oc-R1B9W981WGB5D0': 'LeventB "LeventB"',
 '#oc-R1BKC1B35FFB0': 'Jeannie G. Munger',
 '#oc-R1BR0ZAELEXWK9': 'Mark',
 '#oc-R1CA7UG1P8ATIR': 'Tom "Tom"',
 '#oc-R1CF9LIM90SAB6': 'William Bagley',
 '#oc-R1CL2JEVUKLP2C': 'ct',
 '#oc-R1CRW5BOSI2J9P': 'Goive',
 '#oc-R1CSQFEG6ZI93U': 'Christy Rebehn',
 '#oc-R1DRI2RP4P2TRV': 'lucas',
 '#oc-R1E24XY86FJXDH': 'SPG',
 '#oc-R1E8ZSZLNTT3DS': 'JM1313',
 '#oc-R1EDGHS9PF6P5L': 'Ryan',
 '#oc-R1EVPJIBW2MROJ': 'Anne',
 '#oc-R1FUPE7GGTPFE9': 'Kightjs',
 '#oc-R1GKUU1PTIDIZ7': 'Barbara Rhoades "Jackie of all Trades"',
 '#oc-R1GL3ZQSX6KWIZ': 'NicoleGr',
 '#oc-R1GRL0HPHZ63DZ': 'kvieweg07',
 '#oc-R1GSBW9QIVY489': 'Ariaceliz "changosdaughter"',
 '#oc-R1GUQD6SLYACOQ': 'p-51 "p-51"',
 '#oc-R1HCNLIP7REOF2': 'Pamela Anne Huntdylan',
 '#oc-R1HFLTAYDCLBBP': 'John Clark Craig "author of Sun Position - Hi...',
 '#oc-R1HM2SQ1WTDKM1': 'J. Voss',
 '#oc-R1HQD1WNMEU87U': 'Wolfsdawn "Wolfsdawn"',
 '#oc-R1I167FM1Y3677': 'dododo18',
 '#oc-R1I7C4F4WUF2PH': 'Buford',
 '#oc-R1I879FCTH83GM': 'NaRiHo',
 '#oc-R1ICFZ7CRFKA5N': 'G. Myers',
 '#oc-R1J5JSGQL7KLJU': 'Jeremy Staunton "JS"',
 '#oc-R1J5M6S2EUERD4': 'jp63',
 '#oc-R1J5TQWBNLGLAY': 'Tara Roseberry-Fahmi',
 '#oc-R1JAV4B39IOXAL': 'silk52',
 '#oc-R1JD33DWYAOZAP': 'Picture Not Perfect',
 '#oc-R1JTKM81Q3DMW8': 'smidgies_mom',
 '#oc-R1K4OCJ8HEIEDY': 'Juli E Ocean "The SilverPen Reviewer"',
 '#oc-R1K507Q6XH9VMK': 'Marleen Davis',
 '#oc-R1KACAU4D4MYL4': 'jubalann',
 '#oc-R1KIN7Z6UZUU8Q': 'BRADLEY  HARDIN',
 '#oc-R1KU5HKP3S3TXV': 'hasper1',
 '#oc-R1L6RAE8NWP3BN': 'Margaret D. Nix',
 '#oc-R1L78OM17TXMS7': 'Becky Campbell',
 '#oc-R1L7FHRQYER2JG': 'G. B. Moyer "Uni-Gold"',
 '#oc-R1L7ZYB2J6ZL8F': 'hockeydon',
 '#oc-R1L8DYA0LM16K3': "Tomorrow's Man",
 '#oc-R1LYYITMLLZNX7': 'Jingle Mama',
 '#oc-R1MHZFBFSNFPJ6': 'Elizabeth A. Pisacrita',
 '#oc-R1MQHH4ZP0XHHN': 'texhorns65',
 '#oc-R1N4A8GFO9QIPE': 'Jonathan',
 '#oc-R1N9YSUKSTV2M0': 'Ellen A Hack',
 '#oc-R1O2TLB33QH80R': 'LW',
 '#oc-R1OE1OPY34LOC8': 'D',
 '#oc-R1OGEG6X7R7642': 'The Truth',
 '#oc-R1OL5ERW8B6QV2': 'great packing and shipping',
 '#oc-R1OM1RTTXEI93C': 'Steve Dale "Nutrition Enthusiast"',
 '#oc-R1OTWY0232JAF9': 'Laura Taranowski "Laura T"',
 '#oc-R1OXVJ55Q3COZC': 'cori "cori"',
 '#oc-R1P45E92XO67UX': 'T Bone',
 '#oc-R1PG9RG4BE0TUO': 'Emmie',
 '#oc-R1PJZHS0R7NSIU': 'R. Saylors',
 '#oc-R1PY268XD9G99L': 'Curtis McGraw "xbr"',
 '#oc-R1PZMXFC48NDDQ': 'Anne "Anne"',
 '#oc-R1Q3A53FLEUYGJ': 'justice4all72',
 '#oc-R1QC32X44AD5TM': 'kvieweg07',
 '#oc-R1QHGBT11WAS7G': 'Mike Wallace',
 '#oc-R1QPS7FOBXKEUI': 'Jamie Jewell',
 '#oc-R1R9YA2J51EY0A': 'Christy Rebehn',
 '#oc-R1S6OJV4N0J07C': 'Sheryl',
 '#oc-R1SA5IJKJKB5NX': 'PALA "Reluctant Reviewer"',
 '#oc-R1SGV4TDC886PI': 'wgb "Morning Joe"',
 '#oc-R1SUH4ULVHVEZS': 'J. Kleine "coffeelover51"',
 '#oc-R1SX2Y5STGHSSG': 'Michelle Edwards',
 '#oc-R1T7FSRRR9M1QJ': 'Kim Silver',
 '#oc-R1TNRTD1MQTVYM': 'R. Kennedy "Ryan"',
 '#oc-R1U8FAII0QYOT3': 'G. Little "value seeker"',
 '#oc-R1UHB5HAUGHE85': 'Robert C. Harvey',
 '#oc-R1UO6NAAGVBW7Z': 'Justitia',
 '#oc-R1VHP4GD3MVIGG': 'jenningstime',
 '#oc-R1VRD09DW4H2HI': 'Nick Alec',
 '#oc-R1WBED904KMM5': 'Phillip Guyton',
 '#oc-R1WIBE7UA1Y7XY': 'dee',
 '#oc-R1WMLZ1CW1ZSJC': 'gogolink',
 '#oc-R1WRQ4QI1JPZZ1': 'Jas0320',
 '#oc-R1WT8QXGZCW9RU': "Joanne O'Malley",
 '#oc-R1XE00JQIJIPUH': 'TK',
 '#oc-R1XJQX1ZZBPD5E': 'jfb',
 '#oc-R1XK2SYVVK4FZA': 'K. E. Peek',
 '#oc-R1Y9492Y54C7A4': 'S. C. Proctor',
 '#oc-R1YD35BFIT2RUP': 'J. Voss',
 '#oc-R1YKEOXC41C6Y5': 'T. Bukowski "holleta"',
 '#oc-R1Z5421E1DH837': 'ddwa',
 '#oc-R1ZP24MP75MNWZ': 'D. Dobson "unregistered.coward"',
 '#oc-R1ZR5L29T4LSAE': 'M. Lafferman',
 '#oc-R20T17BLTNKA3': 'LFPV',
 '#oc-R22FWY5KIS6MKC': 'Coffee and Spiritual Jeans',
 '#oc-R23OHF8O4IALHG': 'Travis Crites',
 '#oc-R242XV3ENMZELQ': 'Pockets',
 '#oc-R24BVFW0IAWS5B': 'Brian Syvertson',
 '#oc-R24N4GHDU6SMAP': 'Richard Fisher "pischachs pro"',
 '#oc-R24NJ9EAUPQTE2': 'Miss ReadsALot "reading with a coffee in my h...',
 '#oc-R24XB0UZD3K53O': 'David',
 '#oc-R251I5HN964H2W': 'HAC44',
 '#oc-R256HNV7LG55X9': 'J. Roche "JEPR"',
 '#oc-R25DHM3G5QFH5N': 'Debbie Mary',
 '#oc-R25H00YXSICYHM': 'MIKE JUREWITCH',
 '#oc-R26DKYCO954ZWP': 'P. Cannon',
 '#oc-R26TNGDC3GD6FW': 'Sween',
 '#oc-R270MXCQO96SW5': 'Seaturtle',
 '#oc-R27B4266ZZ0GPP': 'Gary Denton "Liberal Anti-Authoritarian"',
 '#oc-R282JHQB4ARKZ7': 'C. Meyer',
 '#oc-R28I1AL1ZAZLXL': 'M. Brown',
 '#oc-R28KFK52X6G9Z7': 'Clowny "Critic"',
 '#oc-R2A6KSO0JFR6PV': 'SR',
 '#oc-R2AET84WTB0SX5': 'IntoTheCloud',
 '#oc-R2AQ2GKHB7YE1E': 'Laurette Bradley',
 '#oc-R2AR9GGE9WVSC3': 'N. Mazor',
 '#oc-R2ARZA89FMQ7NU': 'A. Price "Quality shopper"',
 '#oc-R2AS2BHTRBGEBA': 'thekannon',
 '#oc-R2B86BJE5FNKXX': 'Mrs. Krinklebine "piddly"',
 '#oc-R2BYJKL21N7DU9': 'Trisha',
 '#oc-R2BZW5PLDUZHM1': 'Stephen J. Lewan',
 '#oc-R2C1Z26VPQHGIF': 'Big Rpgh',
 '#oc-R2C7F72WD2NEUW': 'Michael A. Wittie "Michael"',
 '#oc-R2CFWMT7MB8XMR': 'Carol Jagger',
 '#oc-R2CIG5JYXHVPEE': 'Scott R. Custer',
 '#oc-R2CQETFE39ZTAT': 'V. Wiedemann "2 avid readers"',
 '#oc-R2CQW2ZOJH2NRW': 'Mr. Ronald D. Parsell',
 '#oc-R2CW09YNAH2H4R': 'CaliChef',
 '#oc-R2DNMJY02UXQMM': 'Glen',
 '#oc-R2E9Y1E0G5IIB1': 'Big Jake',
 '#oc-R2EGPCEJ9FAS3': 'Jay D. Miller',
 '#oc-R2EJ2GXWIAB437': 'Gus Wirth Jr.',
 '#oc-R2ELH50PWSIEH1': 'iameclectic',
 '#oc-R2F3I37IKVM0H0': 'Addison Dewitt "I\'m nobody\'s fool."',
 '#oc-R2FFR4TJBR8DPD': 'Geek',
 '#oc-R2GDRKIV15IZHW': 'Wes Hood',
 '#oc-R2GESI3K4U8TGQ': 'Dawn Marx',
 '#oc-R2GHQVSQ3AYTE9': 'RON STRANG',
 '#oc-R2GI4MU6AGGBTS': 'Malcolm Cochrane "brodog"',
 '#oc-R2GTLUGFBPA5AP': 'Sharon Lovell',
 '#oc-R2H4ECH3FPPM6Y': 'Mr. Louis B. Kavanau',
 '#oc-R2H7Z7E2A1H0F3': 'Sunshine789',
 '#oc-R2H8OTJ9JBKYOD': 'Trysta',
 '#oc-R2H9Q62BAPDLIG': 'Robert Jarvis',
 '#oc-R2HLGNHVIDQ0G1': 'Susan K. Schoonover "Sue Yingling"',
 '#oc-R2HV1DPND8MYK5': 'Andrew J. Mcmenemy "PA ANDY"',
 '#oc-R2HV5DBJZSGU39': 'Tess',
 '#oc-R2HV741PDFL75Q': 'Patrick J Fitzgerald',
 '#oc-R2HWL8UHAIMFRS': 'Backroads "Scatter-brained book fan"',
 '#oc-R2HXSXDP1HIXZP': 'garyyager',
 '#oc-R2I5AU09IL1R95': 'ShoNoMrc',
 '#oc-R2I5KQKFCNQ239': 'Mary Kean "Valkyrie911"',
 '#oc-R2I6W317S4FHAU': 'Chicago-Land Bruce "Bruce in Chicago"',
 '#oc-R2I896V302UXAQ': 'Elke B. Speliopoulos',
 '#oc-R2IAZ7AQCNXD53': 'lisa',
 '#oc-R2J2UPVOOKS7ER': 'Lit Prof',
 '#oc-R2J5IEG05RZUL4': 'A. Newhouse',
 '#oc-R2J9Z0H7P6GG8C': 'William B. Ford "munnsmet"',
 '#oc-R2JBOY3BVQLMNQ': 'Elaine B.',
 '#oc-R2JCC3EI274MDF': 'J. Ryan',
 '#oc-R2JEJ80Z975G82': 'Ryan H.',
 '#oc-R2JLACXZ4EBXI8': 'lin',
 '#oc-R2K1Z48V7YY9HT': 'D. E. Biegun',
 '#oc-R2K9AJ2LWO7ZUJ': 'Danny Yu',
 '#oc-R2KCIJHXTXT0KU': 'marec1',
 '#oc-R2KYB1AMCHLOG3': 'Linda S. Davis',
 '#oc-R2KZUCYX33VHUR': 'Lisa M.',
 '#oc-R2L42GUIFKV0Z3': 'Geoff Wood',
 '#oc-R2M17G7NB9RAIV': 'Scott Asher "ashertopia"',
 '#oc-R2M3KDKLRT9W0L': 'David Rupert',
 '#oc-R2MG5C3DMRU8Q0': 'J. Robson "Reflective Artist & Product Designer"',
 '#oc-R2MOR8M0C3KSK7': 'Janet Maggio',
 '#oc-R2MV6EKMKO78L2': '********',
 '#oc-R2MZW62KGLBDIU': 'Amy Goebel Padgett "AGP"',
 '#oc-R2N91H7F3QEXMS': 'GalenaAlaska',
 '#oc-R2NE8ISCFVOS3': 'kateness',
 '#oc-R2NJ6AJ4FFIY2X': 'Bocceman',
 '#oc-R2NTZIG65LJ0RB': 'louise s "louise s"',
 '#oc-R2O4E9SPR08RNA': 'Jacqueline A. Julian "dalspring"',
 '#oc-R2OOQE7R5EB0NO': 'Rosemary Resler',
 '#oc-R2OXMDDCX58FIL': 'MamaBear007 "MamaBear007"',
 '#oc-R2PKZHP3H5OVJW': 'e',
 '#oc-R2PS459CVHZKJL': 'Fun Indasun',
 '#oc-R2PWOJTSJYZRGQ': 'Unprofessional Techie',
 '#oc-R2QKJ7I0V53JJB': 'BullDog',
 '#oc-R2QRIFHKMX74HY': 'J. Walters',
 '#oc-R2R3OTFDNJN9JQ': 'Kerri DeRienzo',
 '#oc-R2R45EEG606NCJ': 'Leah Maines',
 '#oc-R2R4QWSMO8I8YB': 'Dubs',
 '#oc-R2R9TFK97GIFOR': 'Michael Sobers',
 '#oc-R2RIBQ0M86DM9W': 'JOC',
 '#oc-R2RUAJOPVDG63Z': 'alabama girl',
 '#oc-R2RZWR5FKM97NR': 'Robert B. Meyers "sylert"',
 '#oc-R2SMX6LG3FFJ32': 'Andy L. "NC_Andy"',
 '#oc-R2SVV5KG3GN1O1': 'tedT',
 '#oc-R2SXB3L5XPV97Y': 'ORTriathlete',
 '#oc-R2T2GL1NAC2UMH': 'BGE',
 '#oc-R2T3K0QPL1KWSY': 'Taryn Gallagher',
 '#oc-R2T4CCHC2AETHN': 'mineolacoffee',
 '#oc-R2UH5M9R81FAQG': 'Alicia Dudek',
 '#oc-R2ULR70UT6GZPQ': 'K. Harris "Film aficionado"',
 '#oc-R2UN2SBMGXH9E9': 'Alicia Johnson',
 '#oc-R2VCBU1KSEHMA9': 'Macintosh Sauce "It\'s all about the sauce..."',
 '#oc-R2VJK62IOXO4D8': 'W. Morris',
 '#oc-R2VJODW8FRRXEJ': 'K. Ward "Love to shop"',
 '#oc-R2VNVRO5VLW2AC': 'Kevin F',
 '#oc-R2W0C6DARSLJ0S': 'M. Hammon',
 '#oc-R2W66Y63G88976': 'M. Gravel',
 '#oc-R2W8VENK53JCEI': 'JMOGH "JMOGH"',
 '#oc-R2WCS9J1BU09FS': 'Grateful Veteran',
 '#oc-R2WWXB8WMOMUNQ': 'A. Telispeople "Chi Peeps"',
 '#oc-R2XC4EZLEGDB6T': 'kathleenga',
 '#oc-R2XHEXATHR854G': 'Babs',
 '#oc-R2XPA5PDTSKFER': 'J. Cox',
 '#oc-R2XZVYL146WRFL': 'Iron Man "JON"',
 '#oc-R2YAIJQPFQ3JVB': 'Linda Bille "Coffee Girl"',
 '#oc-R2YJB3QYVBIRGM': 'Paul',
 '#oc-R2YKMI6BFV0RA7': 'Marjorie Crews "MJC"',
 '#oc-R2YPVWM76O2TFX': 'Just Loves Books',
 '#oc-R2YWTE7IVV5F6T': 'D. Daughtrey',
 '#oc-R2Z2P7V8UEXH2': 'J. Phillips',
 '#oc-R2ZARZZGRIU309': 'NoLimit24_FJ "J Nolan"',
 '#oc-R2ZB2HNJXTDCXG': 'A. Telispeople "Chi Peeps"',
 '#oc-R2ZRD0CUP3Z9E2': 'C. Jones',
 '#oc-R2ZSS4BRWR3VA6': 'RoseC',
 '#oc-R2ZTU0FEJBQXE7': 'Shannie "Shan"',
 '#oc-R30850MDCRIZJ5': 'Joan M. Johnson Berg',
 '#oc-R30FGA51P8U33R': 'carolynm58',
 '#oc-R30MZZEFKNU7ED': 'Dissatisfied Customer',
 '#oc-R30NTIGTVO109I': 'Jeffrey',
 '#oc-R30QU6O45MNX74': 'pkw99',
 '#oc-R30XCON3EIQHI': 'traceyfo',
 '#oc-R315KFC1BY6GTY': 'Dan Haase',
 '#oc-R317IV2026UMOV': 'Lawrence "audiobook lover"',
 '#oc-R31AI08Q9HLVF1': 'Brian Hawkinson',
 '#oc-R31XNAUKEWAHVL': 'Gary',
 '#oc-R320S5SAY7LRDE': 'Beldini',
 '#oc-R32L0MMVMR414V': 'M. Sutyak',
 '#oc-R32PRO9R9OEIBB': 'Robert Britt',
 '#oc-R32YZ2ME31DM7Y': 'Mary J. Pagels',
 '#oc-R3376HJIKZWS95': 'Maria Rietz "Meows3"',
 '#oc-R3378ONZT42ML5': 'Christopher J. Kellum "Christopher J. Kellum"',
 '#oc-R33A2HF65FLYXF': 'bjg',
 '#oc-R33RCX8AAPSI9': 'n',
 '#oc-R34EIQSQ0VKF2N': 'GSpen',
 '#oc-R34PBE41YSFXZ4': 'Melvin Fields "Tech Expert"',
 '#oc-R34PQ2ORKQ6WCD': 'OutlawPoet "OutlawPoet"',
 '#oc-R34PXGSW6K9Q9A': 'D. Mcdermott',
 '#oc-R34S5XXW58I012': 'Frances A. Tracy',
 '#oc-R355S2078GNWM4': 'Cafe Carmen',
 '#oc-R35AMNGET9A7FO': 'Yomikee',
 '#oc-R35HNNIL3NF69J': 'Busy Mom',
 '#oc-R35T9L1WI8990M': 'Because Cheaper is Better "-A.S."',
 '#oc-R35TWGEXHF2L3G': 'J. Jacob',
 '#oc-R35YUP5T21KW2U': 'disappointed',
 '#oc-R366Y9INLHMV2U': 'DJNH',
 '#oc-R369KQZWAJY2YO': 'JanetFor',
 '#oc-R36D56XD4RTHQP': 'Kosmo',
 '#oc-R36DOJP1ZSZ9Y8': 'BC',
 '#oc-R36LVL0A37GRQP': 'V. Koenig',
 '#oc-R36NOPFPZZQ3NN': 'Dougie Fresh',
 '#oc-R375ESEP91C1CN': 'C. Schaeffler',
 '#oc-R37BIITTCKZKLJ': 'canjcooks',
 '#oc-R37JLBWIMO5N0A': 'A. Koren "sharing quality"',
 '#oc-R37M7HQ8B2G9PJ': 'John Adams',
 '#oc-R380SZNCHL41PP': 'S. Abrahamson',
 '#oc-R38HGDZKOSW736': 'Cynthia D. "CinDee"',
 '#oc-R38Y2XBDC1YSK9': 'George',
 '#oc-R396SZDPAXVXPQ': 'ANHR',
 '#oc-R398TCQXEE8FB1': 'Lawrence Gaudet',
 '#oc-R39CJD8FGFI1JF': 'J',
 '#oc-R39HI2LQ9LHV32': 'stephanie',
 '#oc-R39Y8ZC7RCUAAV': 'ObjectiveJoe',
 '#oc-R39ZT6SB1RCP8Y': 'Jason D. Smith "Jason Smith"',
 '#oc-R3AW0XGZ06Q03O': 'The Truth',
 '#oc-R3B6K46ORGN7AU': 'mags',
 '#oc-R3B9REW4I3ER89': 'Dave',
 '#oc-R3BDHOTWFGS67B': 'Bethany',
 '#oc-R3BFL0KFPM66H6': 'Bun',
 '#oc-R3BRVT76VCL439': 'Ethan C. Emmett',
 '#oc-R3CW88JBWTEZ0I': 'JW',
 '#oc-R3CWEI1SAZ2U7H': 'NyiNya "NyiNya"',
 '#oc-R3DERHJ8UWPZZ': 'Adam "ashaef"',
 '#oc-R3DTQ8B7WD49S2': 'J. Clalyton',
 '#oc-R3E0F1HJ1LBJWI': 'The Glasscocks',
 '#oc-R3EDGA2893DM4Y': 'Edward Walker "ednpatty"',
 '#oc-R3EITU8JKC29II': 'Willie McKay',
 '#oc-R3F0UDHOQC1RNU': 'Trevor J. Flannigan',
 '#oc-R3F6J64D5R7UUJ': 'Sharon',
 '#oc-R3G2DD7ARNLNFA': 'gppbb',
 '#oc-R3G821DX8EOJ3R': 'J. Brown',
 '#oc-R3GE8AOJOSUJVX': 'Christine',
 '#oc-R3GJXOUGQ0IA7N': 'Scott K "scottk"',
 '#oc-R3HMF6ODAC2R4': 'J. Phillips',
 '#oc-R3HOUN9277BVTK': 'Rebecca',
 '#oc-R3IPOATS03565U': 'Maxine J. Ransing "Max"',
 '#oc-R3IX025L68IP59': 'Cynthia Raxter',
 '#oc-R3J6DE3FJLIVMZ': 'W. Sopchek',
 '#oc-R3JW8TXVFCRK3B': 'MommyP',
 '#oc-R3JZ6TGV9JTPFQ': 'L. Matthews',
 '#oc-R3KP9BGLT1K7J0': 'RhodesVan3000',
 '#oc-R3L1AW830LGH1I': 'madmcd "mam"',
 '#oc-R3L950A9DQXOGF': 'daddy10',
 '#oc-R3LBXC8M092D8N': 'rampageous_cuss',
 '#oc-R3LI5WJM4WD02C': 'Adryenn Ashley "Outspoken Pundit"',
 '#oc-R3LM5CZ7IBV2YB': 'Dale B Schafer',
 '#oc-R3LN1O1XAS2EMI': 'Maggie',
 '#oc-R3LTCHVHU0MIXA': 'Sheryl',
 '#oc-R3LV7INTW9K7D9': 'Kristin',
 '#oc-R3LYZ89G4KQ9KG': 'Shelly Itkin "Book Lover and Mom"',
 '#oc-R3MJOHGV9SQCJR': 'Gift Card Recipient "Slap Happy North"',
 '#oc-R3N5HMRMTDMPKA': 'D. DeWitt',
 '#oc-R3NL6BE4JWA8Y0': 'Diana Gwilt',
 '#oc-R3NZKZGLJEKBN3': 'Summeroz',
 '#oc-R3O01FKT4K21GV': 'John from Buffalo',
 '#oc-R3OS88C8I7GSS5': 'Jason P. Pumphrey "the movie & music man"',
 '#oc-R3OTZHRKTMTV8W': 'Karen L. Sandoval',
 '#oc-R3OV5TCJV2MN6E': 'Sandra K. Blogg "Kemm"',
 '#oc-R3OZAR95DCO73U': 'Deb',
 '#oc-R3PPTIPFBA7NPQ': 'Joel',
 '#oc-R3PX3DR3EXNU72': 'Jorasims',
 '#oc-R3Q4YFF8R7XVYR': 'Lori K. Chambers "shopaholic"',
 '#oc-R3Q8Z35P2D8VOW': 'Mrich419',
 '#oc-R3QDBWZKB5TOBB': 'L. Marks',
 '#oc-R3QF72YRJKFCDK': 'Olivia\'s Kiki "Doting grandmother"',
 '#oc-R3QVJD4FKUQKIF': 'Joanne Johnson "Jodon"',
 '#oc-R3R54OYMF3T6ZJ': 'Boppy2006 "Vic"',
 '#oc-R3R59Z61N8QY2S': 'K. Gormley',
 '#oc-R3RG7FCOOEHM2H': 'shaggy',
 '#oc-R3RHKFUZ0HQ136': 'Bart Hayward',
 '#oc-R3RMG4F3JAN4CE': 'Dez "Dez"',
 '#oc-R3RQNMHS7481DE': 'Bryan Carey "Bryan Carey"',
 '#oc-R3RXA1UY9TAE87': 'L. Lenz',
 '#oc-R3S1S27T3LPH8J': 'eshap2',
 '#oc-R3SMJW9GF11SUY': 'jasper K',
 '#oc-R3SRKE3YQ2BNES': 'Carol Daley "Marinesgirl"',
 '#oc-R3T49QLEHSLO8Q': 'Pen Name',
 '#oc-R3TXZAQ0JD85LR': 'C. F. Hill "CFH"',
 '#oc-R3TZTZQ7UHNM8Y': 'Bernadette',
 '#oc-R3UC6GDIA79G96': 'Roszee P "Paully"',
 '#oc-R3UMKLJEZX4B0D': 'Jim McIntyre',
 '#oc-R3V1B3CQ6XXZLA': 'Jloeber',
 '#oc-R3V5XARFZHV0IR': 'Mickey Di',
 '#oc-R3VHILCW5IVHL8': 'Georgia Bird',
 '#oc-R3VLTV54QF1D75': 'CC',
 '#oc-R3VPYGC8EAPLES': 'NAT "Nat"',
 '#oc-R3W5DW4JKJT228': 'Mamaw',
 '#oc-R40PWE1BFHMT2': 'Coffee lover',
 '#oc-R4X2FBRWXLYMF': 'G. Heyde "Java Junkie"',
 '#oc-R5ERXCL0DL1I4': 'cin',
 '#oc-R5GQH7DGZRMMN': 'CurlySou1',
 '#oc-R5QN5V5M8J4L7': 'twright',
 '#oc-R5TUA8ZSYSNSE': 'Dee',
 '#oc-R5VRHDEVUCFI6': 'Lydia H.',
 '#oc-R67F980SN7SDY': 'THOMAS M. Murray "Rajidad"',
 '#oc-R6LF0WYR2C9SB': 'brown1829',
 '#oc-R6W25ZJLA53PO': 'Mel',
 '#oc-R6XZUO4F9WYVS': 'Michael',
 '#oc-R74G863TQ9F2K': 'Nechama Nafisi',
 '#oc-R7CI6KRBWW53G': 'TexasJane "TexasJane"',
 '#oc-R7FDPX5Y0AZUZ': 'Lawrence D. Clayton "Boomlarry"',
 '#oc-R7J3WU9V5ZB4H': 'kay sabow "KAY"',
 '#oc-R7XOEZJN6YQMF': 'Taryn Gallagher',
 '#oc-R8D0D8LAOD2Z9': 'Happy Retiree',
 '#oc-R8EZLM74R071X': 'jalien',
 '#oc-R8K4UTB2ZEOZB': 'Christopher Mackay',
 '#oc-R8SSRU94GFLRC': 'Linda Young "On line shopper"',
 '#oc-R92ECWR98ATCZ': 'NCSILVERLADY',
 '#oc-R9U5CVQD4NCMK': 'Teresa Fox "goldenhalo"',
 '#oc-RASEEQYZ52553': 'Zebra1',
 '#oc-RAX7795F3126S': 'C. Frick "La Gringa"',
 '#oc-RB52UIGZ2JPE2': 'ekochman',
 '#oc-RB8HBT019NHW9': 'Peter J Allen',
 '#oc-RBBMGDEYVK78C': 'DonMikey "donmikey"',
 '#oc-RBNUNZ8FNWU65': 'HaloMOM117',
 '#oc-RBQSDDFG0AUE1': 'Linda Van de Wiele',
 '#oc-RBXFUOOK09Q2B': 'Katherine A. East "Ak Cloudwoman"',
 '#oc-RCP7C3JO7G9TM': 'lizzie',
 '#oc-RDF6K8UXX3UVI': 'Robert Moore',
 '#oc-RDMOLOJCV5VD0': 'Jeremy Staunton "JS"',
 '#oc-RDPBV6VI4WKJ': 'Ozgoddess "BBB"',
 '#oc-RDQ0MYQYDGGEK': 'David Hicks',
 '#oc-RDSEWEOB68RX0': 'Tybeej',
 '#oc-RDU2EN0HNUORJ': 'Jennifer S. ~ "In God We Trust"',
 '#oc-REBMPH49Y3GI7': 'Bocceman',
 '#oc-REQKM7TDXBKS7': 'Denise Ward',
 '#oc-REZAFY2PGSQN9': 'Melissa Velik',
 '#oc-RF8LJUCBBM24R': 'D. Scheeler "Proud American"',
 '#oc-RFNGP3MWMAU76': 'Sherrie Smith',
 '#oc-RFWZSYZF1V4YC': 'Harold',
 '#oc-RGL0JHVXBFQFA': 'J. Groves',
 '#oc-RH8POR57FMI5X': 'DawnCassata',
 '#oc-RHAJQCQUG9JVW': 'Boy#4',
 '#oc-RHK2VGC38EULK': 'Eric',
 '#oc-RHT38THTXPDMH': 'M. B. RICHARDSON',
 '#oc-RHTFVCLEUIUY0': 'Joan',
 '#oc-RIYZNCDB7XQJX': 'Vanessameg',
 '#oc-RJDA7PI12TR29': 'Coffee drinker',
 '#oc-RJT1BEPHJZD4U': 'Shawn',
 '#oc-RJYKFX28LX84J': 'Ern',
 '#oc-RK0HRTGDS8TF3': 'Peter G. Keen "rabidreader"',
 '#oc-RKAMX6ABRGA1W': 'Kate',
 '#oc-RKF6AFGSSGCT7': 'piccoli',
 '#oc-RKLMXRCYYJPC8': 'dododo18',
 '#oc-RKU1BA6XFA3Q4': 'Mary Santos',
 '#oc-RKXSYHUNJ1G19': 'jamout',
 '#oc-RL12MW8DW922U': 'hrmajsty',
 '#oc-RL7Z9CN30TRXQ': 'javarich',
 '#oc-RMBODWNVK1H1D': 'K. "daisy4given"',
 '#oc-RMDH1MTJZQDHR': 'Tanya',
 '#oc-RMHV320CGAS0O': 'toby',
 '#oc-RMN5A4BC01XJV': 'Tom1166',
 '#oc-RMZ34LEZUO6EY': 'Carrot Top',
 '#oc-RNFCOA3SE6CUA': 'ontheroad',
 '#oc-RNMDR27B0MP1I': 'MO',
 '#oc-RNUW40M25M4I4': 'Calayan Rail',
 '#oc-ROAVF7R8RDJ67': 'Little Bird',
 '#oc-RODMQLZAXFCUG': 'Tim Drake "Author and Journalist"',
 '#oc-ROHUCFFNAIA4K': 'doughman65',
 '#oc-RPFZ3SFR2VXWA': 'F. Schamberger',
 '#oc-RPH2M7F3XVPSE': 'Richard E. Kelley',
 '#oc-RPS46SRDKTRZI': 'Thomas F. Harper Jr.',
 '#oc-RQYR6P3WQGC32': 'WillyB.',
 '#oc-RRG64YR1U9G1Z': 'Alicia Dawn Cordrey',
 '#oc-RRLGQFNKXAD2Z': 'C. Frick "La Gringa"',
 '#oc-RRXQ9WWDNJRMG': 'Walt Ski',
 '#oc-RS2VFRNYYRVUG': 'Andrew Ellington',
 '#oc-RSY6AL41NKUEH': 'R. Kuck "Judee"',
 '#oc-RSZMLJGJRON5W': 'M. A. Ramos',
 '#oc-RTHI84TEHN2AA': 'Meg',
 '#oc-RTQ6CJNOWGDA5': 'Adam',
 '#oc-RTT6JCOO6YA39': 'Aaron Martin',
 '#oc-RTTUMLKENL704': 'G. Dash',
 '#oc-RUCLMJ3IUSWPC': 'Mad Max',
 '#oc-RUHNHDHN9HG4Z': 'Gordon Bell',
 '#oc-RV1CL5MB39LEK': 'Gretchen M. Koch "fate_looking_away"',
 '#oc-RVL1KG7B9OCG7': 'Bosoxy "coffee lovah"',
 '#oc-RWPIA8Q9VWJ40': 'dabpigpen',
 '#oc-RWTD5HRIL253R': 'calamity jane',
 '#oc-RX4GIINK3NRIJ': 'coffee once-in-awhile',
 '#oc-RXCJ97CMQTXVA': 'cb',
 '#oc-RXFX0AFFBDSJN': 'Steve Burns',
 '#oc-RXJP29KQC7JFG': 'Chef Parm',
 '#oc-RXKX7XDTBUWZI': 'Ouiser B.',
 '#oc-RXLWWUASQSA4L': 'Guiltyr1',
 '#oc-RXSNTEGUD5F26': 'aelaine',
 '#oc-RY2YBCTS1DTT5': 'mvdeyarmond',
 '#oc-RY4FGUQDYXIIB': 'Snag "snag"',
 'A00489763J7YUCSN6CP7K': 'Andrea Llyod',
 'A015565634RZNSDLJBE5M': 'SassySteph',
 'A06364072LBY1F3ING9XN': 'AprylRon H.',
 'A07112861KSNE1D0ZA1NO': 'Canon Fan',

In [10]:
missing_names['UserId'].map(name_map)

10616     NaN
25509     NaN
38874     NaN
47923     NaN
49800     NaN
67077     NaN
106550    NaN
121819    NaN
125452    NaN
137613    NaN
163191    NaN
172462    NaN
211846    NaN
268648    NaN
297275    NaN
306751    NaN
331647    NaN
358674    NaN
431598    NaN
440825    NaN
461668    NaN
490412    NaN
491728    NaN
515436    NaN
517676    NaN
560446    NaN
Name: UserId, dtype: object

In [11]:
# Profile name and Missing summary
data[['ProfileName', 'Summary']].query("ProfileName.isna() or Summary.isna()").shape

data[data["ProfileName"].isna() & data["Summary"].isna()]

Empty DataFrame
Columns: [Id, ProductId, UserId, ProfileName, HelpfulnessNumerator, HelpfulnessDenominator, Score, Time, Summary, Text]
Index: []

They are not related!

-------

## **2. Data Cleaning**

Now that you have identified the issues in raw data, let's clean them step-by-step.

**F. Datetime Conversion:** Convert the `Time` column (Unix timestamp in seconds) into a proper pandas `datetime` format using `pd.to_datetime(..., unit='s')`.

**G. Handling Missing Text Values (Smart Imputation):** 
- **G1. Recovering Profile Names:** Since users might have multiple reviews, a missing `ProfileName` might have a known `ProfileName` under the same `UserId` in another row. Check if there are such cases, therefore use this information to impute the missing values.
- **G2. Fallback Imputation:** Fill any *remaining* missing values in `ProfileName` with `'Unknown'`, and fill missing values in `Summary` with `'No Summary'`.

**H. Duplicates:** If any duplicated rows exist, drop them using `.drop_duplicates()` and verify the shape of your DataFrame afterward.

In [12]:
# To do
# F. convert Time to datetime
data["Time"] = pd.to_datetime(data["Time"], unit='s')
data.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,2011-04-27,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,2012-09-07,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,2008-08-18,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,2011-06-13,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,2012-10-21,Great taffy,Great taffy at a great price. There was a wid...

In [13]:
# G1. Recovering Profile names
# Check if there is a known ProfileName under the same UserId

# data.where(data.query())

# G2. Feedback Imputation
data["ProfileName"] = data["ProfileName"].fillna("Unknown")
data["Summary"] = data["Summary"].fillna("No Summary")

In [14]:
# H. Duplicates
# Drop Id column first because Id are all unique
print("Dropping Id column")
# data = data.drop(columns=['Id'])

# Check for all duplicate rows
# data[data.duplicated(keep=False)].sort_values(by=["UserId", "Text"])

print("Duplicated rows: ", len(data[data.duplicated()]))


print("Before dropping duplicates", data.shape)
data = data.drop_duplicates()
print("After dropping duplicates", data.shape)

Dropping Id column
Duplicated rows:  0
Before dropping duplicates (568454, 10)
After dropping duplicates (568454, 10)

-------

## **3. Feature Transformation**

Feature engineering helps turn raw fields into more useful analytical features.

**I. Rating Classification (`Status`):** Create a new column named `Status` based on the review rating (`Score`): 

- `'High'` if `Score >= 4`
- `'Medium'` if `Score == 3`
- `'Low'` if `Score <= 2`

**J. Temporal Extraction (`Year`):** Extract the year from your converted `Time` column and store it in a new column called `Year`.

**K. Metric Calculation (`HelpfulnessRatio`):** Create a column `HelpfulnessRatio` by dividing `HelpfulnessNumerator` by `HelpfulnessDenominator`. Handle division-by-zero cases (e.g., set to 0 when `HelpfulnessDenominator == 0`).

In [15]:
data.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,2011-04-27,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,2012-09-07,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,2008-08-18,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,2011-06-13,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,2012-10-21,Great taffy,Great taffy at a great price. There was a wid...

In [16]:
# To do
# I. Rating Classification
bins = [0, 2, 3, 5]
labels = ["Low", "Medium", "High"]

data["Status"] = pd.cut(data["Score"], bins=bins, labels=labels)
data.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text,Status
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,2011-04-27,Good Quality Dog Food,I have bought several of the Vitality canned d...,High
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,2012-09-07,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...,Low
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,2008-08-18,"""Delight"" says it all",This is a confection that has been around a fe...,High
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,2011-06-13,Cough Medicine,If you are looking for the secret ingredient i...,Low
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,2012-10-21,Great taffy,Great taffy at a great price. There was a wid...,High

In [17]:
# J. Extract year from Time
data["Year"] = data["Time"].dt.year

data.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text,Status,Year
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,2011-04-27,Good Quality Dog Food,I have bought several of the Vitality canned d...,High,2011
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,2012-09-07,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...,Low,2012
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,2008-08-18,"""Delight"" says it all",This is a confection that has been around a fe...,High,2008
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,2011-06-13,Cough Medicine,If you are looking for the secret ingredient i...,Low,2011
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,2012-10-21,Great taffy,Great taffy at a great price. There was a wid...,High,2012

In [18]:
import numpy as np
# K. Create HelpfulnessRatio column (HelpfulNum / HelpfulDen); handle division-by-zero (set to 0)
data["HelpfulnessRatio"] = np.where(
    data["HelpfulnessDenominator"] > 0,
    data["HelpfulnessNumerator"] / data["HelpfulnessDenominator"],
    0
)

data.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text,Status,Year,HelpfulnessRatio
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,2011-04-27,Good Quality Dog Food,I have bought several of the Vitality canned d...,High,2011,1.0
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,2012-09-07,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...,Low,2012,0.0
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,2008-08-18,"""Delight"" says it all",This is a confection that has been around a fe...,High,2008,1.0
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,2011-06-13,Cough Medicine,If you are looking for the secret ingredient i...,Low,2011,1.0
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,2012-10-21,Great taffy,Great taffy at a great price. There was a wid...,High,2012,0.0

In [26]:
# Export data as a csv file to use Lab 2
PATH = "datasets/cleaned_amazon_product_reviews.csv"

data.to_csv(PATH, index=False)
print("Data saved to", PATH)

Data saved to datasets/cleaned_amazon_product_reviews.csv

-------

## **4. Grouping & Aggregation**

**L. Most Reviewed Products:** Group by `ProductId`. Find the **top 5 products** with the highest number of reviews.

**M. User Activity:** Group by `UserId`. Find the **top 5 most active reviewers** (users with the most reviews) and calculate their average review `Score`.

**N. Product Metrics:** For the top 5 products identified in Question **L**, use `.groupby()` and `.agg()` to compute both the average `Score` and total count of reviews.

In [19]:
# To do
# L. Most Reviewed products Group by ProductId
print("Top 5 products with the highest number of reviews")
data.groupby("ProductId").size().sort_values(ascending=False).head()

Top 5 products with the highest number of reviews

ProductId
B007JFMH8M    913
B002QWP8H0    632
B002QWHJOU    632
B002QWP89S    632
B0026RQTGE    632
dtype: int64

In [20]:
# M. user Activity group by UserId & Calculate their average review Score
print("Top 5 most active reviews")

user_activity = data.groupby("UserId").agg(
    review_count=("Score", 'size'),
    average_score=("Score", "mean")
)
user_activity.sort_values(by="review_count",ascending=False).head()

Top 5 most active reviews

                review_count  average_score
UserId
A3OXHLG6DIBRW8           448       4.535714
A1YUL9PCJR3JTY           421       4.494062
AY12DBB0U420B            389       4.647815
A281NPSIMI1C2R           365       4.841096
A1Z54EM24Y40LL           256       4.453125

**N. Product Metrics:** For the top 5 products identified in Question **L**, use `.groupby()` and `.agg()` to compute both the average `Score` and total count of reviews.

In [21]:
# N. compute avr score and total count of reviews for top 5 products
most_reviewed_products = data.groupby("ProductId").agg(
    review_count=("Score", "size"), # can be any field btw, not just Score
    average_count=("Score", "mean")
).round(2)  # we can add .round after the whole agg func

top_5_most_reviewed_products = most_reviewed_products.sort_values(by="review_count", ascending=False).head().reset_index()  # reset ProductId from index into column label
top_5_most_reviewed_products

    ProductId  review_count  average_count
0  B007JFMH8M           913           4.58
1  B002QWP8H0           632           4.59
2  B002QWHJOU           632           4.59
3  B002QWP89S           632           4.59
4  B0026RQTGE           632           4.59

-------

## **5. Combining and Reshaping Data**

**O. Combining Datasets (`pd.merge`):** Create a small lookup DataFrame named `product_catalog` containing:

- `ProductId`: The top 5 product IDs from Question **L**
- `Category`: Assigned categories (e.g., `'Beverages'`, `'Snacks'`, `'Gourmet'`, `'Pet Supplies'`, `'Organic'`)

Perform an **inner join** (`pd.merge`) between your aggregated product metrics from Question **N** and `product_catalog`.

**P. Reshaping Data (`pd.pivot_table`):** Create a pivot table using `pd.pivot_table()` to summarize review volume:

- **Index (Rows):** `Year`
- **Columns:** `Status` (`High`, `Medium`, `Low`)
- **Values:** Count of reviews (`Score`)
- **Mean:** average score per category of `Status`.
- Fill missing cells with 0.

**Q.** How does the platform perform over the years?

In [22]:
# To do
# O. Combining Datasets (pd.merge)
    # Create a lookup df product_catalog containign top 5 products and 5 categories
product_catalog = pd.DataFrame(
    {
        'ProductId': top_5_most_reviewed_products['ProductId'],
        'Category': ['Beverages', 'Snacks', 'Gourmet', 'Pet Supplies', 'Organic']
    }
)
product_catalog

merged_product = pd.merge(top_5_most_reviewed_products, product_catalog, how='inner')
merged_product

    ProductId  review_count  average_count      Category
0  B007JFMH8M           913           4.58     Beverages
1  B002QWP8H0           632           4.59        Snacks
2  B002QWHJOU           632           4.59       Gourmet
3  B002QWP89S           632           4.59  Pet Supplies
4  B0026RQTGE           632           4.59       Organic

In [23]:
# P. Pivot table to summarize review volume
pivot_table = pd.pivot_table(
    data,
    index='Year',
    columns='Status',
    values='Score',
    aggfunc=['count', 'mean'],
    fill_value=0
).round(2)

pivot_table

C:\Users\eungl\AppData\Local\Temp\ipykernel_17876\1306149491.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(
C:\Users\eungl\AppData\Local\Temp\ipykernel_17876\1306149491.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

        count                 mean
Status    Low Medium    High   Low Medium  High
Year
1999        0      0       6  0.00    0.0  5.00
2000        3      0      29  1.00    0.0  4.90
2001        4      1       8  1.25    3.0  4.75
2002        3      0      70  2.00    0.0  4.83
2003       12      8     112  1.17    3.0  4.76
2004       58     18     485  1.17    3.0  4.83
2005      142     53    1140  1.58    3.0  4.87
2006      783    428    5460  1.33    3.0  4.84
2007     2164   1326   18810  1.42    3.0  4.83
2008     3542   2171   28450  1.36    3.0  4.82
2009     6496   3762   45068  1.40    3.0  4.83
2010    12317   6248   67319  1.36    3.0  4.83
2011    24937  13022  125340  1.36    3.0  4.82
2012    31576  15603  151480  1.35    3.0  4.81

In [24]:
# **Q.** How does the platform perform over the years?
yearly_data = data.groupby('Year')['Score'].agg(['count', 'mean'])

yearly_data

       count      mean
Year
1999       6  5.000000
2000      32  4.531250
2001      13  3.538462
2002      73  4.712329
2003     132  4.325758
2004     561  4.392157
2005    1335  4.445693
2006    6671  4.313446
2007   22300  4.391345
2008   34163  4.345344
2009   55326  4.300365
2010   85884  4.198838
2011  163299  4.143804
2012  198659  4.117885

**Q.** How does the platform perform over the years?
> Over the years, the review counts has grown gradually from 6 in 1999 to almost 200,000 reviews in 2012. With the increase of review counts, the average review score also seem to gradually decrease from perfect 5 score in 1999 to dropping as low as 3.5 in 2001, but bounced back the next year up to 4.7, and slowly decrease until it reached 4.1 in 2012.

# **Further Reading**

- `Pandas` Data Wrangling Cheat Sheet: https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

- Chapter 6-8, Python for Data Analysis by Wes McKinney: https://wesmckinney.com/book/

- `Pandas` Apply, Transform, Map: https://pandas.pydata.org/docs/user_guide/basics.html